apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aniverse
spec:
  type: ExternalName
  externalName: aniverse-db.xxxxxx.us-east-1.rds.amazonaws.com # REPLACE WITH YOUR RDS ENDPOINT
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: aniverse
type: Opaque
stringData:
  MYSQL_USER: aniverse_user
  MYSQL_PASSWORD: aniverse_password # REPLACE WITH YOUR DB PASSWORD
  MYSQL_DATABASE: aniverse
